version: 2
jobs:
  build:
    docker:
      - image: theorangeone/docker-pandoc
    steps:
      - checkout
      - run: make
      - store_artifacts:
        path: m3pi-python.pdf
      - store_artifacts:
        path: m3pi-none.pdf
