version: 2
jobs:
    build:
        docker:
            - image: theorangeone/docker-pandoc
        working_directory: ~/m3pi-docs
        steps:
            - checkout
            - run: make
            - store_artifacts:
                path: docs.pdf
                destination: docs.pdf
