name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: theorangeone/docker-pandoc

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build document
      run: make

    - name: Store built PDF (m3pi from Python)
      uses: actions/upload-artifact@v3.1.3
      with:
        name: m3pi-python.pdf
        path: m3pi-python.pdf
    - name: Store built PDF (m3pi from nothing)
      uses: actions/upload-artifact@v3.1.3
      with:
        name: m3pi-none.pdf
        path: m3pi-none.pdf
